<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Pedidos' => 'the pedid',
    '¿Qué es Transportes ya?'=> 'What is Transportes Now',
    'Inicio'=> 'Home',
    'Activities' => '',
    'Activity 1 Amount' => '',
    'Activity 1 Date' => '',
    'Activity 1 Type' => '',
    'Activity 2 Amount' => '',
    'Activity 2 Date' => '',
    'Activity 2 Type' => '',
    'Activity 3 Amount' => '',
    'Activity 3 Date' => '',
    'Activity 3 Type' => '',
    'Address 1' => '',
    'Address 2' => '',
    'Address Information' => '',
    'Admin' => '',
    'Agent' => '',
    'Agents' => '',
    'Attach panel' => '',
    'Back to Search' => '',
    'Cash Value' => '',
    'City' => '',
    'Client' => '',
    'Dashboard' => '',
    'Detach panel' => '',
    'Effective Date' => '',
    'English' => '',
    'Fixed' => '',
    'Free Wd' => '',
    'French' => '',
    'Fund Breakout' => '',
    'Fund Fixed Perform' => '',
    'Fund Fixed Value' => '',
    'Fund Growth Perform' => '',
    'Fund Growth Value' => '',
    'Fund Risk Perform' => '',
    'Fund Risk Value' => '',
    'General' => '',
    'Growth' => '',
    'History' => '',
    'ID' => '',
    'Language' => '',
    'Loan Amount' => '',
    'Log in' => '',
    'Login' => '',
    'Logo image' => '',
    'Logout' => '',
    'Owner Name' => '',
    'Password' => '',
    'Performance' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Policy' => '',
    'Policy Dashboard' => '',
    'Policy Number' => '',
    'Policy Value' => '',
    'Product' => '',
    'Recent Activity' => '',
    'Rider/Benefit ' => '',
    'Risk' => '',
    'Search' => '',
    'Search...' => '',
    'Spanish' => '',
    'State' => '',
    'USA' => '',
    'User name' => '',
    'Username' => '',
    'You do not have sufficient permissions to access.' => '',
    'Zip' => '',
    '{copy} {year} OSOC' => '',
    'Dashboard data' => '@@@@',
    'Euro' => '@@@@',
    'United States' => '@@@@',
    'Zip Code' => '@@@@',
    'Gridstack' => 'Gridstack',
];
